WIP: Add Position() to Firmware interface
linuxboot/fiano pull request #317
Opened 2020-05-15 10:39 UTC by karlodwyer

[Original Issue here](https://github.com/linuxboot/fiano/issues/164)

@xaionaro asked on the opensource firmware slack for suggestions around implementing this idea. The approach suggested was to publish a PR and work it out form there, so he and I talked a bit about this.

Some things to note:
* We understand it is not good to export a visitor `PositionUpdater` from uefi, but we are open for discussion on how to fix it.
* This change and `Assemble` probably need more testing to give us more assurance that we aren't regressing anything.

2020-05-15 12:09 UTC, JulienVdG commented
Hello, first I've not looked into the code yet, but regarding your point about `PositionUpdater` above you can place it in the visitor package along with other visitors.
There is already coupling between the two package anyway (assemble or table cannot work without knowing about each uefi type).
A visitor is not required to provide cli (again assemble is a good example, there is no `RegisterCLI` in assemble.go)
hope this helps.

2020-05-15 12:36 UTC, xaionaro commented
> Hello, first I've not looked into the code yet, but regarding your point about `PositionUpdater` above you can place it in the visitor package along with other visitors.

The problem is:
We want to get objects with updates offsets from `uefi.Parse`. So this called is required to be called from `uefi.Parse`. And if we put this visitor to `visitors` we get a circular dependency:
`uefi` -> `visitor` -> `uefi`.

This circular dependency could be broken if we will move types (like `BIOSPadding`) to a separate package (like `./pkg/uefi/types`). In this case the new visitor could be implemented in `./internal/visitors` and used from both packages `uefi` and `visitors`. But since it is changes in the skeleton of the project it would be nice to understand if this approach is approved :)

2020-05-28 02:39 UTC, GanShun requested changes
This is an interesting approach, however I'd much rather have the visitor in pkg/visitors. 

The way I would avoid the cyclic dependency is to call updatePositions not from uefi.Parse, but from pkg/utk/utk.go, in the Run function right before other visitors are executed. This also ensures that if we are calling utk on an extracted directory, the positions are also updated. Right now I think it'll only work if you call utk on a bios image.

2020-05-28 02:39 UTC, GanShun commented on pkg/uefi/flash.go
> +// Position returns the absolution position of the node in the firmware image.
*absolute

2020-05-28 02:39 UTC, GanShun commented on pkg/uefi/update_positions.go
> +// Visit applies the Table visitor to any Firmware type.
*PositionUpdater

2021-02-08 21:50 UTC, GanShun commented on pkg/uefi/section.go
> +// Position returns the absolution position of the node in the firmware image.
absolute*

2024-09-19 19:47 UTC, rminnich commented
I am closing this, for lack of interest.

2024-09-29 17:31 UTC, orangecms commented
I'm interested, see #321

2024-10-02 04:05 UTC, closed without merging

2024-10-02 04:05 UTC, rminnich commented
I don't think this one is going to get finished.