Allow ExtendedSize to be shown in utk JSON
linuxboot/fiano pull request #380
Opened 2022-05-08 20:25 UTC by AkechiShiro

Pull request, allowing `ExtendedSize` for UEFI to be shown in the JSON output, in order to get to fix issue fiedka/fiedka#76

2022-05-08 20:40 UTC, orangecms commented
Yea, that's it! Could you please rephrase or just remove the comment?
Fiano can be used in other tools as well, so it shouldn't suggest any tight coupling. Maybe include something in the commit message rather, along the lines of "This allows for use with other tools".

Thank you! :-)

2022-05-08 20:42 UTC, orangecms commented
Ah, and finally, run `gofmt`, the Go formatting tool; its code style is very opinionated, and that's what causes the checks to error. 😅

2022-05-08 20:56 UTC, AkechiShiro commented
Thanks for your input on this and help, should I also fix some regression tests which are currently failing due to my change?

2022-05-11 21:28 UTC, orangecms commented
So the failing test is the extract+reassemble test `pkg/visitors/extract_test.go`.

In a first step, I am improving the output. Insead of printing the entire buffer, I print the position and the respective byte, #382

2022-05-12 00:21 UTC, orangecms commented
I gave it another try in #383 by just marshalling the plain `Size` instead, WDYT?

2022-05-12 12:25 UTC, AkechiShiro commented
If we can get to fix the tests using #383, I'm all down for it, but @GanShun should also give us his thoughts on it, I guess if that changes would be alright in the codebase.

2023-09-18 05:08 UTC, rminnich requested changes

2023-09-18 05:08 UTC, rminnich commented on integration/utk_test.go
> +				sedCmd := exec.Command("sed", "-i", "/\"ExtendedSize\": [0-9]*.*/d", path)
we can't have dependencies on sed in a test, can you change how this is done.

2023-09-18 05:08 UTC, rminnich commented on integration/utk_test.go
> +			sedRemove := func(path string) {
you can remove createTempDir if you want and use t.TempDIr()

2024-09-16 15:35 UTC, rminnich reviewed
I got a bit lost with some of what you did in this PR, sorry.

2024-09-16 15:35 UTC, rminnich commented on integration/utk_test.go
> +				sedCmd := exec.Command("sed", "-i", "/\"ExtendedSize\": [0-9]*.*/d", path)
what you can do, instead, is use regexp.ReplaceAll; just read the file in, do the replace, write it out.
os.ReadAll
regexp.ReplaceAll
os.WriteFile
but what I'm wondering: if you don't want ExtendedSize in the test, why did you put it in the JSON? If it's not in the JSON, then the struct member will be zero; is that not good enough?

2024-09-16 15:37 UTC, AkechiShiro commented
I'm sorry as well I forgot I had opened this PR a while ago

2024-09-16 16:45 UTC, rminnich commented
Fixed a different way, see #424 

So if you want to add ExtendedSize you can see how.

2024-09-16 19:06 UTC, orangecms commented
Just for explanation of the original background: Fiedka was not showing size information, but the issue was elsewhere.
The `Size` is exposed and has been integrated in Fiedka, see https://github.com/fiedka/fiedka/issues/76

2024-09-16 20:47 UTC, AkechiShiro commented
So this PR's goal is to add `ExtendedSize` that would be in the UI as well as in the test case, just not using `sed` and `diff` just like in the fix @rminnich mentioned (so that test use only Go Packages)

I guess first thing would be to rebase this PR and solve any conflicts

2024-09-16 20:50 UTC, rminnich commented
I think we may no longer need this PR? Daniel?

2024-09-17 19:22 UTC, closed without merging